import pytest_check as check

from utils import read_tmp_file, Converter


def test_check_transfer(start_client, tmp_path):
    """Check transfer."""

    ## Step 1. Create temp json file to write log (will be deleted after session)
    tmp_client_log_path = tmp_path / "client.json"

    ## Step 2. Start client with temp json file path as --logfile parameter
    start_client("--json", "--logfile", tmp_client_log_path)

    ## Step 3. Read json file generated by client
    client_log = read_tmp_file(tmp_client_log_path)

    receiver_transfer = client_log['end']['sum_received']

    # Converting bytes to MBytes, bits to MBits
    size = Converter.bytes_to_mbytes(receiver_transfer['bytes'])
    bandwidth = Converter.bits_to_mbits(receiver_transfer['bits_per_second'])

    ## Step 4. Check Size
    ### Step 4. Size should be more 5 MBytes
    check.greater(size, 5, "Size is not greater than 5 MBytes.")

    ## Step 5. Check Bandwidth
    ### Step 5. Bandwidth should be more 40 MBits/sec
    check.greater(bandwidth, 40, "Bandwidth is not greater than 40 MBits/sec.")
